version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  worker:
    container_name: worker
    build: ./app
    command: celery -A celery_worker worker --loglevel=info --pool=solo
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - app
    environment:
      - REDIS_URL=redis://redis:6379/0

  flower:
    image: mher/flower
    container_name: flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_PERSISTENT=True
      - FLOWER_STATE_SAVE_INTERVAL=10000
      - FLOWER_DB=/etc/db/flower.db
    ports:
      - "5555:5555"
    volumes:
      - ./flower/storage:/etc/db/
    depends_on:
      - redis

  streamlit:
    container_name: streamlit
    build: ./streamlit
    environment:
      - APP_URL=0.0.0.0:8000
    ports:
      - "8501:8501"
    depends_on:
      - app
      
